### ISSUE TITLE
smithlab_cpp Did not Come with methpipe

### ISSUE THREAD

**Issue by imk1** [smithlabcode/methpipe#102]
When I cloned methpipe, I was not able to install it.  I realized that this was because smithlab_cpp had not been cloned along with methpipe.  In fact, the src directory had an empty smithlab_cpp folder.  I ended up fixing this by cloning it separately into the src directory.  It would be great if this could be fixed or clarified in the documentation.  Thanks!

**Comment by bdecato** [comment]
Hi Irene,

Thanks for using our pipeline.  Did you use the --recursive flag to clone
the repository?  I just tried per the instructions in the README.md file at
https://github.com/smithlabcode/methpipe and had no issues.

In general, using the --recursive flag will be better than cloning
smithlab_cpp separately, since we associate a specific commit of
smithlab_cpp with the methpipe source.  If we make development changes to
the smithlab_cpp codebase that aren't incorporated into methpipe yet (which
I don't think we have), it may not work as intended.

Let me know, thanks!!

Ben

On Wed, Jan 18, 2017 at 11:15 AM, Irene Kaplow <notifications@github.com>
wrote:

> When I cloned methpipe, I was not able to install it. I realized that this
> was because smithlab_cpp had not been cloned along with methpipe. In fact,
> the src directory had an empty smithlab_cpp folder. I ended up fixing this
> by cloning it separately into the src directory. It would be great if this
> could be fixed or clarified in the documentation. Thanks!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_smithlabcode_methpipe_issues_102&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=SpXCeWczJOWPYEneTspxwg&m=gaZ519QbhZYH_tn2f4P-RtEQTNCViPFUwYsfc_sm_1E&s=PEyqO-JBxJMbC4sr-HEIReBVg4AC2IAMI0EdoaQRwnA&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AHBe0MTzMIuM-5F3i471dmLmT20JoJUgOxks5rTmTdgaJpZM4LnRxv&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=SpXCeWczJOWPYEneTspxwg&m=gaZ519QbhZYH_tn2f4P-RtEQTNCViPFUwYsfc_sm_1E&s=M2LAvfK5Cky6BfZ0XR1KrU7gvI3NWZLND9vwDWmrsRM&e=>
> .
>



-- 
-- 
Benjamin Decato
PhD Candidate
Computational Biology Section,
Department of Biological Sciences,
University of Southern California
1050 Childs Way, RRI 408M
Los Angeles, CA 90089-2910

**Comment by andrewdavidsmith** [comment]
I think the documentations says to clone recursively, did u do that?

Sent from my iPhone

On Jan 18, 2017, at 11:15 AM, Irene Kaplow <notifications@github.com<mailto:notifications@github.com>> wrote:


When I cloned methpipe, I was not able to install it. I realized that this was because smithlab_cpp had not been cloned along with methpipe. In fact, the src directory had an empty smithlab_cpp folder. I ended up fixing this by cloning it separately into the src directory. It would be great if this could be fixed or clarified in the documentation. Thanks!

-

**Comment by imk1** [comment]
I did not try the --recursive flag.  The documents did not make it clear that I needed to clone recursively in order for things to work.  (It seemed like that was an option only if I wanted to be a beta tester.)  It would be great if you could clarify that for future users.  Thanks for getting back to me so quickly!

**Comment by andrewdavidsmith** [comment]
Be aware that if u get smithlabcpp separately versions might not agree. Use a tat ball unless u want unstable code. If the latter then do recursive pls

Sent from my iPhone

On Jan 18, 2017, at 11:25 AM, Irene Kaplow <notifications@github.com<mailto:notifications@github.com>> wrote:


I did not try the --recursive flag. The documents did not make it clear that I needed to clone recursively in order for things to work. (It seemed like that was an option only if I wanted to be a beta tester.) It would be great if you could clarify that for future users. Thanks for getting back to me so quickly!

-

**Comment by imk1** [comment]
Thanks!
