### ISSUE TITLE
Problem with CpGs with 0 Reads

### ISSUE THREAD

**Issue by imk1** [smithlabcode/methpipe#104]
I tried calling hyper-methylated regions in the way described (inverting the methylation signal and then calling hypo-methylation).  I ended up getting a number of hyper-methylation regions in places that had no methylation.  I looked at the data, and all of those places had CpGs, but those CpGs had 0 supporting reads.  After removing the CpGs with 0 supporting reads, it seems like the problem might be gone.  It would be great if someone could look into this.  Thanks!

**Comment by bdecato** [comment]
Hi Irene,

I tested your scenario by downloading the Human sperm methylome from Molaro et al. (2011) and inverting the methylation levels for chromosome 19 two different ways: one with a conditional to check for 0 coverage (inverting if coverage > 1, otherwise not changing the methylation level) and one indiscriminately inverting the methylation state (exactly as described in the manual).  I also explicitly changed some coverage values where a hyper-MR should exist before inverting, inverted both ways, and called hmrs.

In both scenarios, I didn't get a difference in the output.  Can you provide me a minimal example that illustrates the issue?

Theoretically the output should be identical: we model CpG site methylation levels as beta-binomial so that their contribution to the HMR (or hyperMR) state is proportional to our confidence of the true methylation level at the site (which is determined by coverage).  If any weight is being given to zero coverage sites, it's a bug.

Thank you,

Ben

**Comment by imk1** [comment]
I am so sorry for taking so long to get back to you.  It looks like the bug was on my end and not yours.  Thanks for trying to help me out!

**Comment by bdecato** [comment]
I'm glad things worked out! Don't hesitate to reach out if you have any additional questions, and thanks again for using our stuff. Closing this!
