### ISSUE TITLE
question on proportion table

### ISSUE THREAD

**Issue by lxcfuji** [smithlabcode/methpipe#106]
Hi Smith Lab,

I'm generating my proportion table with a very small sample size dataset. 
And in your example, I see you have 3 subjects for each case/column. Is there any minium requirement for sample size in each case?
for ample, I have a variable/case with 2 subjects in control and 5 subjects in treatment, can I adjust for this variable?
Thank you!

**Comment by bdecato** [comment]
Hi @lxcfuji,

Thanks for using our pipeline. In the future, please ask questions on our google group (methpipe@googlegroups.com) so that other community members can answer and our responses are indexed by search engines.

We used 3 subjects for each case/column as an example, but there is no minimum requirement for sample size in each case. After multiple testing correction of your p-values, you may find that with such a low sample size you are underpowered to identify individual sites that are differentially methylated.

One good approach is to run Radmeth for detection of differentially methylated *regulatory elements* such as promoters and enhancers. This decreases the number of statistical tests you are performing from 28 million CpGs (for human) to ~25,000 (RefSeq promoters), and while it sacrifices some resolution, is a good move for low sample size experimental designs. I recommend downloading a regulatory annotation from the UCSC genome browser (such as RefSeq genes), using command line tools to get the promoter (we historically, but nonsensically, use +/-1kb), get the average methylation level in each promoter via `roimethstat`, and make your proportion table with those values.

I hope this helps, thanks again for using our stuff!

Ben
