### ISSUE TITLE
How to compare amr in different groups 

### ISSUE THREAD

**Issue by wkl1990** [smithlabcode/methpipe#117]
I got the amr of each sample using amrfinder.  First, I do not know the meaning of the 4th column in the output bed file. Secondly, because I have many samples in groups, how could I get the common amr within groups and the specific amr in different groups?

**Comment by bdecato** [comment]
Hi @wkl1990,

Thanks for using our pipeline. It appears the 4th and 5th column are not explicitly explained in the manual: I apologize for that and will update the manual to include them.

The 4th column holds two fields separated by a colon. The first is the name of the AMR (AMR1, AMR2, etc.) with the numbers not being contiguous due to filtering by FDR correction of p-values. The second is the number of reads in the sample overlapping the AMR. The 5th column is the score, either computed by likelihood ratio test or BIC (by default, LRT).

As far as getting common AMRs within groups and the specific AMRs in different groups, bedtools is  great for "genome arithmetic" (http://bedtools.readthedocs.io/en/latest/index.html). I recommend looking into the `bedtools intersect` and `bedtools merge` functions.

I hope this helped!

Ben

**Comment by wkl1990** [comment]
Hi @bdecato ,

Thank you very much for your reply. It really helps. 

I still have a question. The number and mean size of the AMR in each sample is various. The number range from hundreds to thousands and the mean size range from 5kb to 40 kb. I am not sure if this is true. By the way, I called the AMR using amrfinder and the default parameters.

Best,
Wang

**Comment by bdecato** [comment]
This definitely sounds like a bug: AMRs should be on the order of a few kilobases and should not be as frequent as you describe.

Let me look into it: I think it may have something to do with the likelihood ratio test option. Try using the BIC score option and let me know what kind of results you get.

**Comment by wkl1990** [comment]
Hi @bdecato 

I have tried the BIC method for all samples using the -b parameter. The number of BIC AMR range from two thousand to ten thousand and the mean size range from 5kb to 20 kb.

**Comment by wkl1990** [comment]
Hi @bdecato 
Both the likelihood ratio and BIC method return so many and large AMRs. To reduce the regions, what parameters should I adjust?

**Comment by wkl1990** [comment]
Hi @bdecato 
I got an interesting finding. The large AMR detected by amrfinder are more likely located in the centromere regions in my data. Such as chr1:121,483,923-142,536,340, chr2:92,317,962-95,327,781, and chr8:43,835,383-46,838,942. I wonder if I could filter them based on this phenomena. Besides, the scores in LRT and BIC are very different, they are very small (like p value) in LRT but negative in BIC.  I am sorry I still do not know what the scores mean in LRT and BIC, respectively.

**Comment by bdecato** [comment]
Hi @wkl1990,

For LRT, the 5th column is a p-value for whether the two-allele model fits significantly better than the single-allele model or not. For BIC, look up Bayesian information criterion: it is a form of model selection that penalizes increasing numbers of parameters in your model. The higher the BIC score, the better the 2-allele model fits.

One good thing to check is whether known imprinting control regions are being called AMRs (such as the ICRs for *GNAS*, *H19*/*IGF2*, etc). In the past I've also filtered for the top 1,000 AMRs based on size or BIC score for downstream analysis.

I am currently debugging this issue but it may take awhile. A solid way to ensure that the AMRs you're getting are good is to go with the original version of `amrfinder` that was used in the paper describing it. You can find that in methpipe version 3.1.1 (available [here)](https://github.com/smithlabcode/methpipe/releases). I am using those as the good AMRs to identify any issues in the current segmentation.

**Comment by andrewdavidsmith** [comment]
This issue is not clearly stated. It seems like a general request for help in usage of a tool, and guidelines for doing analysis, rather than an issue.
