### ISSUE TITLE
GCC

### ISSUE THREAD

**Issue by hmyh1202** [smithlabcode/methpipe#120]
can U provide a lower version of GCC requirement to install the soft? 
my gcc version is  4.4.7, and I can`t update it

**Comment by bdecato** [comment]
Hi @hmyh1202,

You have two options in this case:

1. You can try to download a previous version of methpipe from the "releases" section on github, specifically one prior to the migration to C++11. Those will have most of the functionality of modern methpipe but should be compatible with that version of gcc.

2. You can download the latest version of gcc (https://gcc.gnu.org/releases.html) and install it locally, and then have the makefiles in methpipe point to that version of gcc, rather than your default. This is probably the better option of the two.

I hope this helps!

Ben

**Comment by andrewdavidsmith** [comment]
@hmy1202 please let us know if you are able to do one of these options.

If you go for option (2), which we recommend, and encounter any difficulty, please contact us directly and we might be able to offer some help.

On Jan 15, 2018, at 6:50 PM, Benjamin Decato <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @hmyh1202<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_hmyh1202&d=DwMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=2ti3K9K1XjkPszCPHB82Aw&m=Ds4DflbkCbCit6MWurCb46PF4-EDvGCt8c3rBRWrQjI&s=Upk1f-mJt810pQPxM_qMLOiwXCUfzCwqQF02_EGeaeI&e=>,

You have two options in this case:

  1.  You can try to download a previous version of methpipe from the "releases" section on github, specifically one prior to the migration to C++11. Those will have most of the functionality of modern methpipe but should be compatible with that version of gcc.

  2.  You can download the latest version of gcc (https://gcc.gnu.org/releases.html<https://urldefense.proofpoint.com/v2/url?u=https-3A__gcc.gnu.org_releases.html&d=DwMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=2ti3K9K1XjkPszCPHB82Aw&m=Ds4DflbkCbCit6MWurCb46PF4-EDvGCt8c3rBRWrQjI&s=uI4zFvFgECDveBFWf6Ox6sfUdC3JDbAKlDm1JnsWrFc&e=>) and install it locally, and then have the makefiles in methpipe point to that version of gcc, rather than your default. This is probably the better option of the two.

I hope this helps!

Ben

**Comment by bdecato** [comment]
Any update on this @hmyh1202? Hope things worked out!

**Comment by andrewdavidsmith** [comment]
Deciding to stay with relatively recent gcc.
