### ISSUE TITLE
HMR score column larger than 1000, error from bedToBigBed

### ISSUE THREAD

**Issue by jdnukem** [smithlabcode/methpipe#129]
Hi, when I run bedToBigBed on my *.hmr file, I get the following error:
"score (###) must be between 0 and 1000"

Since the scores represent CpG's within each hmr, I don't imagine setting scores that are >1000 to 1000 would be the best way around this error.

What would you advise I do?

Thanks!
John

**Comment by bdecato** [comment]
Hi John,

To be honest, since I usually don't use the score in the visualization with bigBed, I typically just create my bigBed file from the first 3 columns (awk them out to a temp file, run bedToBigBed on that temp file, delete temp file).

If you are interested in visualizing the relative CpG density of your HMRs (i.e. useScore=1 on the browser), you could create a normalized score that ranges from 0-1000 from the current score column by dividing each score by the max score and multiplying by 1000 (or however else you want to do it).

Good luck!

**Comment by jdnukem** [comment]
I ended up normalizing the scores, but in retrospect, I will probably just awk the first 3 columns for the future. 

Cheers
