### ISSUE TITLE
Error running hmr & pmd

### ISSUE THREAD

**Issue by hchetia** [smithlabcode/methpipe#167]
Running into an error while identifying hypo-methylated regions in "test dataset".
Snapshot attached.
![image](https://user-images.githubusercontent.com/64626735/94203388-4fbf4380-fe8d-11ea-819d-e2c8924745de.png)

**Comment by hchetia** [comment]
Similar error with "pmd"
![image](https://user-images.githubusercontent.com/64626735/94203527-8eed9480-fe8d-11ea-9136-79b894cfdedb.png)

**Comment by andrewdavidsmith** [comment]
Thanks @hchetia for this! This is an out-dated file format. I would not be surprised if we have forgotten to update something. Can you please give me the source of the file used here? If it was one of our example files, we will need to replace it ASAP. Our current methcounts output format is not the same as a bed format any more, because we now include the context of the site (e.g. CpG, CHH, etc.) and we don't use the redundant pair of start and end positions.

**Comment by terencewtli** [comment]
Hi @hchetia,

Thank you for pointing this out. I have just updated the methpipe test data. You can try redownloading and running `hmr` and `pmd` on the respective samples.

**Comment by hchetia** [comment]
Both hmr and pmd runs successfully on the new test data. Just want to add that the Readme.txt accompanying the test dataset should also be updated for the hmr_plant command.

**Comment by terencewtli** [comment]
I will fix that. Thank you!
