### ISSUE TITLE
the first read problem 

### ISSUE THREAD

**Issue by acgtun** [smithlabcode/methpipe#63]
I got a sam file which is bsmap's result. The first mapping result is as following:
SRR1532539.1    272     chr9_gl000199_random    105295  255     90M     *       0       0       CCTCAAAACACTCCAAATATCCACTTCCAAATAATACAAAAAAAATATTTCAAACCTACTCTATAAAAAAAAATATTCAACTCTATAACT      BBB^bb]`WKTGG_]_ZRYKTRZGTGGGb_]Rb_ZUFc[`edge\H[baSgf_ca^IXXIII[hhhhhhhgc`K_^`accac`cccc^_Z  

However, to-mr gave the following result.
(NULL)  0       0       SRR1532539.1    0       + 

Thanks.

**Comment by mengzhou** [comment]
I canceled the support for bsmap in to-mr, because it seems to have wrong
SAM flag settings. Can you send a path to the SAM file?

Best regards,
Meng

**Comment by acgtun** [comment]
Here it is. Thanks.
/home/rcf-40/haifengc/panfs/bsm_test/bsmap/SRX666252/mpoutsamSRR1532539_1.fastq.sam

**Comment by acgtun** [comment]
/home/rcf-40/haifengc/panfs/bsm_test/bsmap/SRX666252/mpoutsam/SRR1532539_1.fastq.sam

**Comment by mengzhou** [comment]
The chromosome is NULL because that read was flagged as secondary alignment. In to-mr codes, if the read is secondary alignment, the program won't load anything. But this empty read was still printed.

For now just use samtools to filter out secondary alignment prior to running to-mr, because usually you do not need secondary mapping result. You can use the following command:
samtools view -h -S -F 256 INPUT_SAM >  TEMP_SAM
to-mr -m general TEMP_SAM > read.mr

Best regards,
Meng

**Comment by acgtun** [comment]
Hi, Meng,

Thanks a lot. I tried this way, but I got the same error. 

I changed the first read by hand, so don't worry about this issue.

Best,
Haifeng

**Comment by acgtun** [comment]
Hi, Meng,

The number of mismatch is set to 0 after transferring sam file to mr file? Is that correct?. Thanks.

Best,
Haifeng
