### ISSUE TITLE
Support for BWA-meth

### ISSUE THREAD

**Issue by cviner** [smithlabcode/methpipe#70]
It would be great if [to-mr](https://github.com/smithlabcode/methpipe/blob/master/src/utils/to-mr.cpp) could be enhanced to also support [bwa-meth](https://github.com/brentp/bwa-meth).

**Comment by cviner** [comment]
Unless perhaps ```-m general``` is expected to work in this case (I assumed not, since there seemed to be a fair amount of [mapper-specific parsing](https://github.com/smithlabcode/smithlab_cpp/blob/master/SAM.cpp#L266) being done for methylation-sensitive aligners and expect bwa-meth support to have similarities to Bismark)?

**Comment by andrewdavidsmith** [comment]
Thanks for the suggestion. It is extremely difficult to support each mapper, because they often do not accurately document how they do things. But this is something we will consider.

**Comment by cviner** [comment]
Thank you for considering it and for such a rapid reply. I can certainly understand it being challenging to do so. In some of my tests, I have observed that bwa-meth to often performs better than Bismark and usually runs in a fraction of its time and space complexity, so I prefer it.

Regardless, thanks for this great software, and in particular MLML—I am finding it immensely useful!

**Comment by mengzhou** [comment]
I just checked the `bwa-meth` output. Since `bwa-meth` uses `bwa` for the mapping duty, the `-m general` option will work fine. Because `bwa` is perhaps the best mapper at using SAM flags properly.

The only problem for using `general` is the number of mismatch per alignment will not be converted. But this will not affect any current `methpipe` component, so it's ok.

**Comment by cviner** [comment]
This is great news; thanks!

I do however currently get the following error when attempting this:

    Processed 1000000 records
    terminate called after throwing an instance of 'std::length_error'
      what():  basic_string::_S_create
    Aborted (core dumped)

**Comment by mengzhou** [comment]
I just fixed this with the latest commit. It's actually due to a discordant
pair of mapped reads, e.g. end1 mapping downstream of end2:
                 ----->end1
   <----end2
This kind of alignment will now be skipped and not converted.

Best regards,
Meng

**Comment by cviner** [comment]
Oh, excellent!

Was it not also the case that there was some issue with recording of methylation state, that `bwa-meth` does differently from Bismark? Does the general parsing mode automatically account for this?

**Comment by mengzhou** [comment]
The purpose of `to-mr` is to recover the mapping locations and original
read sequences. If this information can be converted, all other `methpipe`
components will work fine. For now I have not seen any mapper that actually
alter the original read sequences in the output. The other complementary
information included in BAM/SAM, such as the methylation state you
mentioned, will not be used for conversion, because `methcounts` will take
care of methylation related stuff.

Of course if you see any bugs or aberrant conversions in the future, please
let us know and it's greatly appreciated.

Best regards,
Meng

**Comment by cviner** [comment]
That makes sense. I appreciate the detailed explanation.

Thanks for all your work on this. I'm looking forward to using this on `bwa-meth` data!
