### ISSUE TITLE
to-mr output sort-order can differ from sorted input BAM order and from that required by duplicate-remover

### ISSUE THREAD

**Issue by cviner** [smithlabcode/methpipe#71]
```to-mr``` outputs data in a sort-order distinct from that required by ```duplicate-remover```, even when provided with a position-sorted BAM file as input. This prevents one from taking advantage of sorted input files, since it becomes necessary to always sort ```to-mr``` output, prior to input into ```duplicate-remover``` (per the instructions provided in Section 2.2 of the MethPipe manual).

I provide below an example of this problem (only pertinent columns are shown, i.e. columns 1–3, 6 of ```to-mr``` output and 2–4, 9 of the BAM file, as formatted tables):

```bash
samtools view input.sorted.bam | fgrep -m 1 -C 2 3000596
```

FLAG	|	RNAME	|	POS	|	TLEN
------|------------------|-------------------|--------------
163	|	chr10	|	3000512	|	169
83	|	chr10	|	3000581	|	-169
99	|	chr10	|	**3000596**	|	289
163	|	chr10	|	*3000623*	|	122
83	|	chr10	|	3000645	|	-122

```bash
to-mr -o /dev/stdout -m 'bismark' input.sorted.bam | fgrep -m 1 -C 2 '3000595'
```

Chrom.	|	Start		|	End	|	Strand
------|------------------|-------------------|--------------
chr10	|	3000511	|	3000680	|	-
chr10	|	*3000622*	|	3000744	|	-
chr10	|	**3000595**	|	3000884	|	+
chr10	|	3000793	|	3000956	|	+
chr10	|	3000860	|	3001074	|	-

```bash
to-mr -o /dev/stdout -m 'bismark' input.sorted.bam | fgrep -m 1 -C 2 '3000595' | \
duplicate-remover -stdin -o /dev/stdout
```

Chrom.	|	Start		|	End	|	Strand
------|------------------|-------------------|--------------
chr10	|	3000511	|	3000680	|	-
**input not properly sorted:**	|		|		|	
chr10	|	*3000622*	|	3000744	|	-
chr10	|	**3000595**	|	3000884	|	+

```bash
to-mr -o /dev/stdout -m 'bismark' input.sorted.bam | fgrep -m 1 -C 2 '3000595' | \
sort -k1,1 -k2,2n -k3,3n -k6,6 | duplicate-remover -stdin -o /dev/stdout
```

Chrom.	|	Start		|	End	|	Strand
------|------------------|-------------------|--------------
chr10	|	3000511	|	3000680	|	-
chr10	|	**3000595**	|	3000884	|	+
chr10	|	*3000622*	|	3000744	|	-
chr10	|	3000793	|	3000956	|	+
chr10	|	3000860	|	3001074	|	-

**Comment by mengzhou** [comment]
There are cases when `to-mr` cannot handle position-sorted BAM file perfectly. Your input BAM file contains pair-end reads, and in SAM format individual ends are saved separately. However `to-mr` needs to join the matching ends to one fragment (pair), which requires storing reads in the memory until their mates are found.

In your example, the read that was mapped to position 3000596 is an end1 of a pair (according to the flag), but its mate was somewhere after those reads you are shown. I cannot say for sure, because there is no read name information; but looking at the flags, I think it's pretty much the case. The two reads that came successively after this read form a pair; therefore `to-mr` outputs this pair; and the read 3000596 is still kept in memory. I believe its mate was found right after, and then this pair is formed and printed. So the order was changed.

I don't think this is a bug of `to-mr`, but there is not a decent way to keep the sorted order yet. I do personally recommend sorting the BAM file based on read names, because in extreme cases when two ends of a pair locate too far away apart, which could cause the number of reads stored in the memory exceeds the maximum limit, and pairs cannot be correctly joined.

**Comment by cviner** [comment]
Thanks for this detailed explanation. Your explanation makes sense to me, and what you said regarding the paired-end reads and their respective locations in the BAM file is correct.

It's interesting that you'd suggest sorting by read names; I was initially doing that in a previous pipeline, but sorted them by position for input into ```to-mr``` expecting it to maintain the sort order, for suitability of input into ```duplicate-remover```, although I now understand why this would be non-trivial to accomplish.

In the case in which you describe, of ```to-mr``` having more reads stored in memory than it is capable of, what error message(s) would it output (I don't think this occurred in my case, since I'm on a high-memory cluster, but do want to verify this without having to re-sort and re-run all my BAMs)?

**Comment by mengzhou** [comment]
`to-mr` is not very informative in reporting such case (sorry about that). Basically it maintains a hash table with a hard-coded max size, which keeps individual reads as pairing candidates. When the size reaches the limit, `to-mr` will start cleaning the hash table. Reads that are cleaned in this process will be printed as single end.

Because `to-mr` adds a prefix "FRAG" for each fragment in the output, there is a way to find those reads that are mapped as pair but converted as signle-end. I would suggest finding those reads in the converted `.mr` file (grep -v FRAG), and keep their read names; then extract their SAM flag from the BAM file. If one read is mapped with a pair, then the flag bit 0x2 should be set to true by the mapper.

I hope this can provide some help (it might be infeasible for you to do if you have a big BAM file). Because the max size of the hash table is now set to 500, if there is some jackpot in your sorted BAM file, I can imagine there being thousands of consecutive end1 reads which cannot be joined to pairs. This is also why sometimes it is necessary to sort BAM by read name.

**Comment by cviner** [comment]
That's unfortunate, but I appreciate the details and the means of discerning whether this occurred. (It would likely benefit others if you added these details to the end of Section 2.1 of MethPipe's manual.)

I think I can check for that relatively efficiently, using a combination of ```fgrep``` (on the ```to-mr``` output) and [Sambamba](http://lomereiter.github.io/sambamba/)'s [filtering language](https://github.com/lomereiter/sambamba/wiki/%5Bsambamba-view%5D-Filter-expression-syntax) (on the respective BAM file).

Thanks for your help!

**Comment by mengzhou** [comment]
Thanks for helping us improving `methpipe`!

**Comment by cviner** [comment]
My pleasure! :)
