### ISSUE TITLE
removing `pipeline` directory?

### ISSUE THREAD

**Issue by mengzhou** [smithlabcode/methpipe#83]
It is outdated.

**Comment by bdecato** [comment]
@jqujqu and I discussed the functionality of the pipeline directory and I am wondering whether we should remove it or not.  The scripts there do two things:

1) Lift over methylomes from one assembly to another
2) Automate the merging of technical or biological replicates.

We do not use these scripts in house because we have developed scripts more specific to our cluster architecture.  But the description of replicates in the manual and associated scripts might be useful to users wondering how they should treat their methylation data when it has a complicated experimental setup.

Can we get some more opinions on this?

**Comment by bdecato** [comment]
Removed and updated manual.
