### ISSUE TITLE
Convergence condition in TwoStateHMM.cpp

### ISSUE THREAD

**Issue by xjlizji** [smithlabcode/methpipe#91]
`if ((total - prev_total) < tolerance) {
      if (VERBOSE)
    cerr << "CONVERGED" << endl << endl;
      break;
    }`
It will be "converged" once likelihood decreases.

**Comment by andrewdavidsmith** [comment]
It will also be "converged" once likelihood no longer increases. Is it presenting a problem?

**Comment by lizji1992** [comment]
I just have concern that in practical the observation likelihood might not be always strictly increasing before really converges. And I feel like the values of parameters are not converged yet before the likelihood converges based on current criterion.

**Comment by andrewdavidsmith** [comment]
@lizji1992 can you give a bit more detail? Is it true that when the likelihood stops increasing then the values will also not change, and so it must stop? Can you suggest a different convergence criterion?

**Comment by bdecato** [comment]
@andrewdavidsmith @lizji1992  this ambiguity leaves us open to bugs. The likelihood should be monotonically increasing, and if it isn't, we should know about it: that case is distinct from no longer increasing. I think the right convergence criterion is when the *absolute value* of the change in likelihood is below the threshold, along with a warning reporting when likelihood decreases.

I say warning on likelihood decreases because it may not strictly be a bad thing. Anecdotally, I have seen cases where we see a decrease in the likelihood early in iterations followed by a large number of small increases leading to a global value higher than the one before the decrease. This could mean we are "jumping" a valley in the likelihood space and then hiking a taller mountain.

If we decide this is important, I will produce an example segmentation with both convergence criteria for comparison.

**Comment by andrewdavidsmith** [comment]
@bdecato @xjlizji We need a test case for this: some case where the wrong behavior is observed. I suspect numerical issues can mean that we will not be able to see absolute convergence on some large data sets. When we see an extremely small (i.e. almost zero) reduction in likelihood, most of the time the program is behaving properly. I've tried to make sure we never have a reduction in likelihood, but it's really tricky unless we expand out some of the ~optimized numerical calculations.

**Comment by bdecato** [comment]
The lowest effort way to get a test case here would probably be to just include a warning when the likelihood "decreases" and then just wait for that warning to pop up in day-to-day work. Until then any very minor numerical issues wouldn't keep me up at night here.

**Comment by guilhermesena1** [comment]
labeling this as "enhancement" because I don't think this has been implemented yet. If I may chime in: If this is a correctly implemented EM then the likelihood should always increase, and if it decreases due to numerical reasons it should not be by a large value, so I agree with Ben that issuing a warning if it happens, but I don't agree that we need to use absolute value, if tolerance is too small we may fall on a case where likelhood oscillates back and forth between two values higher than tolerance and the program gets stuck in an infinite loop (I think...)

**Comment by andrewdavidsmith** [comment]
Closing due to changing convergence criteria within the tool.
