### ISSUE TITLE
Return values of functions in MethpipeFiles

### ISSUE THREAD

**Issue by andrewdavidsmith** [smithlabcode/methpipe#92]
The functions for reading and writing lines in methcounts files are returning bool values. The reason is to test for success. However, the streams themselves can be used for this, and make the code cleaner. Does anyone have any objection to trying to modify those? I personally don't know of any code it would break.

**Comment by bdecato** [comment]
This is something we should do.  Downstream (heh) we should make our error messages more reflective of the actual error being returned by the stream.

**Comment by andrewdavidsmith** [comment]
I guess you mean “good” and “bad” aren’t reflective enough?

On Mar 24, 2016, at 5:21 PM, Benjamin Decato <notifications@github.com<mailto:notifications@github.com>> wrote:


This is something we should do. Downstream (heh) we should make our error messages more reflective of the actual error being returned by the stream.

**Comment by bdecato** [comment]
Multiple flags among (eofbit, failbit, and badbit) can be set during a single operation.  Each of these flags has specific uses and reasons for it being set.  So if someone tries to read from something that is already at EOF, we would see the failbit and eofbit set, and suggest that they already hit the end of file for instance, rather than just saying "FAILURE" until they figure it out.

**Comment by andrewdavidsmith** [comment]
I was joking.

**Comment by andrewdavidsmith** [comment]
Return values have been updated.
