### ISSUE TITLE
Direct piping of a BAM file into to-mr (missing header error)

### ISSUE THREAD

**Issue by cviner** [smithlabcode/methpipe#97]
Attempting to directly pipe a BAM file into `to-mr` does not appear to function, resulting in a missing header error.

For example:

```bash
sambamba sort -N -l 0 'test.bam' -o /dev/stdout | to-mr -m bismark /dev/stdin
```

fails:

```
[samopen] no @SQ lines in the header.
[sam_read1] missing header? Abort!
```

I was, however, able to work around this issue, by providing the corresponding SAM file to `to-mr`. The below command successfully generated the expected `to-mr` output:

```bash
sambamba sort -N -l 0 'test.bam' -o /dev/stdout | sambamba view -h /dev/stdin | to-mr -m bismark /dev/stdin
```

This issue can also be reproduced using `view` alone. The below also results in the same error shown above:

```bash
sambamba view -f bam 'test.bam' | to-mr -m bismark /dev/stdin
```

Similarly, adding an intermediate `sambamba view -h /dev/stdin` command to the above resolves this issue.

Is this a limitation of `to-mr` that could be amended or is it perhaps invalid of me to attempt to pipe BAM output into `to-mr`, in this fashion?

**Comment by mengzhou** [comment]
The BAM/SAM handling functionality in `to-mr` is directly taken from the `samtools` package, as you can see from the source codes. The open file function always looks for a header no matter the input format. I don't think you can create a legit BAM file without a header, though.

Regarding your question, piping to `to-mr` with a BAM theoretically works, but the problem is that `to-mr` is not smart enough to tell whether the input is SAM or BAM through a pipe. It will try to open the input as an SAM, unless the file name has a ".bam" extension.

**Comment by cviner** [comment]
Could the ability to detect that be added or an argument be provided to specify this? That would enable piping to `to-mr`.

**Comment by andrewdavidsmith** [comment]
We will consider this.

**Comment by cviner** [comment]
Thank you!
